.goreleaser.yml
Fix the `eksdemo version` command. Update to use the new module name
=> fix: version command

README.md
add homebrew install instructions
=> docs: add homebrew install instructions

README.md
Adds a go report banner to the project. Pretty standard for go projects.
=> Add go report card banner to readme

README.md, pkg/application/autoscaling/cluster_autoscaler/cluster_autoscaler.go, pkg/eksctl/eksctl.go, pkg/resource/cluster/options.go
=> add: support for EKS v1.27

pkg/resource/load_balancer/printer.go
Properly identify internal NLB and ALB load balancer types
=> fix: identify internal NLB and ALB in `get load-balancer`

docs/install-awslb.md, pkg/application/aws_lb_controller/aws_lb_controller.go, pkg/application/aws_lb_controller/options.go, pkg/application/ingress.go
Update `aws-lb-controller` to v2.5.2
=> update: `aws-lb-controller` to v2.5.2

docs/install-ebs-csi-driver.md, pkg/application/storage/ebs_csi/ebs_csi.go, pkg/application/storage/ebs_csi/options.go
Update `storage-ebs-csi` to v1.19.0
=> update: `storage-ebs-csi` to v1.19.0

docs/install-edns.md, pkg/application/external_dns/external_dns.go
Update `external-dns` to v0.13.4
=> update: `external-dns` to v0.13.4

pkg/application/kubecost/kubecost_vendor/kubecost_vendor.go
Update `kubecost-vendor` to v1.103.3
=> update: `kubecost-vendor` to v1.103.3

pkg/application/kubecost/kubecost_eks/kubecost_eks.go, pkg/application/kubecost/kubecost_eks/options.go
Update `kubecost-eks` to v1.103.3
=> update: `kubecost-eks` to v1.103.3

docs/install-kubecost.md, pkg/application/kubecost/kubecost_eks_amp/kubecost_eks_amp.go, pkg/application/kubecost/kubecost_eks_amp/options.go, pkg/resource/irsa/irsa.go
Update: `kubecost-eks-amp` to v1.103.3
=> update: `kubecost-eks-amp` to v1.103.3

docs/install-cert-manager.md, pkg/application/cert_manager/cert_manager.go
Update `cert-manager` to v1.12.1
=> update: `cert-manager` to v1.12.1

docs/install-ingress-nginx.md, pkg/application/ingress/nginx/nginx.go, pkg/application/ingress/nginx/options.go
Update `ingress-nginx` to v1.8.0
=> update: `ingress-nginx` to v1.8.0

cmd/install/install.go, cmd/install/uninstall.go, pkg/application/vpc_lattice_controller/gateway_class.go, pkg/application/vpc_lattice_controller/options.go, pkg/application/vpc_lattice_controller/security_group_rule.go, pkg/application/vpc_lattice_controller/vpc_lattice_controller.go
Rename `gateway-api-controller` to `vpc-lattice-controller` and update `vpc-lattice-controller` to v0.0.12
=> update: `vpc-lattice-controller` to v0.0.12

docs/install-kube-prometheus.md, pkg/application/kube_prometheus/kube_prometheus_stack_amp/kube_prometheus_stack_amp.go, pkg/application/kube_prometheus/kube_prometheus_stack_amp/options.go
Update `kube-prometheus-stack-amp` to chart 46.6.0
=> update: `kube-prometheus-stack-amp` to chart 46.6.0

README.md, docs/install-ebs-csi-driver.md
README update for v0.8.0 and typo in EBS CSI tutorial
=> docs: README update for v0.8.0 and typo in EBS CSI tutorial

pkg/eksctl/eksctl.go, pkg/resource/cluster/cluster.go, pkg/resource/cluster/options.go
#31 
Add `--hostname-type` flag to `create cluster`
=> add: `--hostname-type` flag to `create cluster`

pkg/application/ack/apigatewayv2_controller/apigatewayv2_controller.go
Update `ack-apigatewayv2-controller` to v1.0.3
=> update: `ack-apigatewayv2-controller` to v1.0.3

pkg/application/ack/ec2_controller/ec2_controller.go
Update `ack-ec2-controller` to v1.0.3
=> update: `ack-ec2-controller` to v1.0.3

pkg/application/ack/ecr_controller/ecr_controller.go
Update `ack-ecr-controller` to v1.0.4
=> update: `ack-ecr-controller` to v1.0.4

pkg/application/ack/eks_controller/eks_controller.go, pkg/application/ack/eks_controller/fargate_pod_role.go
Update `ack-eks-controller` to v1.0.2
=> update: `ack-eks-controller` to v1.0.2

pkg/application/ack/prometheusservice_controller/prometheusservice_controller.go
Update `ack-prometheusservice-controller` to v1.2.3
=> update: `ack-prometheusservice-controller` to v1.2.3

cmd/create/ack.go, pkg/resource/ack/amp/workspace.go
Add create `add-ack-amp-workspace`
=> add: create `ack-amp-workspace`

cmd/create/ack.go, pkg/application/ack/prometheusservice_controller/prometheusservice_controller.go, pkg/resource/ack/amp/logging_configuration.go
Add: create `ack-amp-logging-configuration`
=> add: create `ack-amp-logging-configuration`

pkg/application/ack/s3_controller/s3_controller.go
Update `ack-s3-controller` to v1.0.4
=> update: `ack-s3-controller` to v1.0.4

README.md, cmd/install/ack.go, pkg/application/ack/iam_controller/iam_controller.go
Add `install ack-iam-controller`
=> add: `install ack-iam-controller`

cmd/create/ack.go, pkg/resource/ack/iam/role.go
=> add: `create ack-iam-role`

pkg/resource/ack/ec2/vpc.go
=> fix: `create ack-vpc`

README.md, cmd/get/get.go, pkg/aws/cloudwatch.go, pkg/resource/alarm/alarm.go, pkg/resource/alarm/get.go, pkg/resource/alarm/printer.go
=> add: `get alarm`

pkg/eksctl/eksctl.go
=> fix: eksctl version check

pkg/application/adot_operator/adot_operator.go, pkg/application/adot_operator/collector_service_account.go, pkg/application/adot_operator/options.go
Update `adot-operator` to ADOT v0.30.0, Operator v0.78.0
=> update: `adot-operator` to ADOT v0.30.0, Operator v0.78.0

cmd/create/create.go, cmd/create/otel.go, pkg/resource/otel/prometheus_cloudwatch.go, pkg/resource/otel/simplest.go
Add create `otel-colletor-simplest` and `otel-collector-prometheus-cloudwatch`
=> add: create `otel-colletor-simplest` and `otel-collector-prometheus-cloudwatch`

pkg/application/appmesh_controller/appmesh_controller.go
Update `appmesh-controller` to v1.12.1
=> update: `appmesh-controller` to v1.12.1

README.md, cmd/root.go, cmd/use_context.go, cmd/version.go
Updates to docs and help messages
=> docs: updates to docs and help messages

README.md
=> Update readme install to the top

README.md, docs/install-vpc-lattice-controller.md
=> add: VPC Lattice tutorial

cmd/install/install.go, cmd/install/uninstall.go, pkg/application/argo/argo_cd/argo_cd.go, pkg/application/argo/argo_cd/options.go
#32 
Update `argo-cd` to v2.7.6
=> update: `argo-cd` to v2.7.7

cmd/create/argo.go, cmd/create/create.go, pkg/resource/argo/guestbook.go
Create `argo-guestbook` example Application CRD to test Argo CD install
=> add: `create argo-guestbook`

pkg/aws/cloudwatch.go, pkg/resource/alarm/get.go, pkg/resource/alarm/printer.go
Fix `get alarm` to include composite alarms
=> fix: `get alarm` to include composite alarms

cmd/create/cognito.go, cmd/create/create.go, pkg/aws/cognito_userpool.go, pkg/resource/cognito/userpool/cognito_userpool.go, pkg/resource/cognito/userpool/get.go, pkg/resource/cognito/userpool/manager.go, pkg/resource/cognito/userpool/options.go, pkg/resource/error.go
Add `create cognito-user-pool`
=> add: `create cognito-user-pool`

cmd/delete/cognito.go, cmd/delete/delete.go, cmd/root.go, pkg/aws/cognito_userpool.go, pkg/resource/cognito/userpool/cognito_userpool.go, pkg/resource/cognito/userpool/manager.go, pkg/resource/cognito/userpool/options.go
Add `delete cognito-user-pool`
=> add: `delete cognito-user-pool`

cmd/get/cognito.go, pkg/aws/cognito_userpool.go, pkg/resource/cognito/domain/cognito_domain.go, pkg/resource/cognito/domain/get.go, pkg/resource/cognito/domain/options.go, pkg/resource/cognito/domain/printer.go
=> add: `get cognito-domain`

cmd/create/cognito.go, pkg/aws/cognito_userpool.go, pkg/resource/cognito/domain/cognito_domain.go, pkg/resource/cognito/domain/manager.go, pkg/resource/cognito/domain/options.go
=> add: `create cognito-domain`

cmd/delete/cognito.go, pkg/aws/cognito_userpool.go, pkg/resource/cognito/domain/cognito_domain.go, pkg/resource/cognito/domain/get.go, pkg/resource/cognito/domain/manager.go, pkg/resource/cognito/domain/options.go
=> add: `delete cognito-domain`

cmd/get/cognito.go, pkg/aws/cognito_userpool.go, pkg/cmd/error.go, pkg/resource/cognito/client/app_client.go, pkg/resource/cognito/client/get.go, pkg/resource/cognito/client/options.go, pkg/resource/cognito/client/printer.go, pkg/resource/cognito/domain/get.go, pkg/resource/cognito/userpool/get.go, pkg/resource/cognito/userpool/manager.go, pkg/resource/cognito/userpool/options.go
=> add: `get cognito-app-client`

cmd/delete/cognito.go, pkg/aws/cognito_userpool.go, pkg/resource/cognito/client/manager.go, pkg/resource/cognito/client/options.go
Add `delete cognito-app-client`
=> add: `delete cognito-app-client`

cmd/install/argo.go, pkg/application/argo/workflows/argo_workflows.go, pkg/application/argo/workflows/options.go
#32 
Update `argo-workflows` to v3.4.9
=> update: `argo-workflows` to v3.4.9

cmd/create/argo.go, pkg/resource/argo/hello_world.go
Add `create argo-hello-world` workflow example
=> add: `create argo-hello-world` workflow example

pkg/aws/amp.go
whitespace lint fix in pkg/aws/amp.go
=> cleanup: whitespace lint fix in pkg/aws/amp.go

cmd/install/argo.go, go.mod, pkg/application/argo/workflows/argo_workflows_cognito.go, pkg/aws/cognito_userpool.go
Add `install argo-workflows-cognito`
=> add: `install argo-workflows-cognito`

cmd/root.go, pkg/helm/helm.go
Include final helm values in debug output
=> debug: include final helm values in debug output

cmd/create/otel.go, pkg/resource/otel/promethus_amp.go, pkg/resource/otel/simplest.go
Add `create otel-prometheus-amp`
=> add: `create otel-prometheus-amp`

.github/workflows/release.yaml, .goreleaser.yml
#72 
Add a GoReleaser workflow to automate the release when a version tag is pushed
=> ci: add goreleaser workflow

.gitignore, .goreleaser.yml, cmd/completion.go, cmd/create/create.go, cmd/delete/delete.go, cmd/get/get.go, cmd/install/install.go, cmd/install/uninstall.go, cmd/root.go, cmd/update.go, cmd/util.go, pkg/resource/network_acl_rule/network_acl_rule.go, scripts/completions.sh
Closes #65 
Add `completion` command
=> add: `completion` command

.github/workflows/release.yaml, .goreleaser.yml
Closes #72 
Release workflow updates Homebrew formula with pull request. Includes installing shell completions.
=> ci: release workflow updates Homebrew formula with pull request

pkg/application/autoscaling/cluster_autoscaler/cluster_autoscaler.go
*Issue #, if available:*\
#32 
Update `autoscaling-cluster-autoscaler` to v1.27.3
=> update: `autoscaling-cluster-autoscaler` to v1.27.3

.devcontainer/devcontainer.json
=> dev: add initial devcontainer.json

cmd/install/example.go, pkg/application/example/ghost/ghost.go, pkg/application/example/ghost/options.go
Add: `example-ghost` application
=> add: `example-ghost` application

pkg/application/velero/options.go, pkg/application/velero/velero.go
#32 
update `velero` to v1.11.1
=> update: `velero` to v1.11.1

cmd/install/ai.go, cmd/install/install.go, cmd/install/uninstall.go, pkg/application/neuron/deviceplugin/device_plugin.go, pkg/application/neuron/deviceplugin/manifest.go
=> add: `ai-neuron-device-plugin`

README.md, pkg/application/autoscaling/cluster_autoscaler/cluster_autoscaler.go, pkg/eksctl/eksctl.go, pkg/resource/cluster/options.go, pkg/resource/nodegroup/nodegroup.go, pkg/resource/nodegroup/options.go
=> add: support for EKS v1.28

cmd/install/install.go, cmd/install/uninstall.go, pkg/application/external_dns/external_dns.go, pkg/resource/cluster/options.go
Update `external-dns` to v0.13.6
=> update: `external-dns` to v0.13.6

pkg/application/kube_prometheus/kube_prometheus_stack/kube_prometheus_stack.go, pkg/application/kube_prometheus/kube_prometheus_stack/options.go, pkg/application/kube_prometheus/kube_prometheus_stack_amp/kube_prometheus_stack_amp.go, pkg/application/kube_prometheus/kube_prometheus_stack_amp/options.go
Update `kube-prometheus-stack` to 51.2.0
=> update: `kube-prometheus-stack` to 51.2.0

cmd/get/get.go, pkg/application/vpc_lattice_controller/vpc_lattice_controller.go
fix: add missing `vpc-lattice` alias
=> fix: add missing `vpc-lattice` alias

pkg/resource/cluster/cluster.go, pkg/resource/cluster/options.go
Add `--disable-network-policy` flag to `create cluster`
=> add: `--disable-network-policy` flag to `create cluster`

README.md, cmd/install/install.go, cmd/install/uninstall.go, pkg/application/headlamp/headlamp.go
Closes: #77
Add headlamp web UI.
=> add: `headlamp` application

pkg/application/storage/efs_csi/efs_csi.go
*Issue #, if available:* #118
Updates EFS CSI driver policy document to reflect the permissions provided by the upstream EFS CSI driver repo in https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/docs/iam-policy-example.json.
=> Update EFS CSI driver policy document

pkg/application/storage/efs_csi/efs_csi.go
Update `storage-efs-csi` to v1.7.0
=> update: `storage-efs-csi` to v1.7.0

README.md
I forgot to document it in #126 😕 
=> docs: Document core-dump-handler in the application catalog

README.md, pkg/application/autoscaling/cluster_autoscaler/cluster_autoscaler.go, pkg/eksctl/eksctl.go, pkg/resource/cluster/options.go
=> add: support for EKS v1.29

docs/install-karpenter.md, pkg/application/autoscaling/karpenter/karpenter.go, pkg/application/autoscaling/karpenter/options.go
Fixes #135 
Update `autoscaling-karpenter` to v0.33.2
=> update: `autoscaling-karpenter` to v0.33.2

docs/install-karpenter.md, pkg/application/autoscaling/karpenter/karpenter.go, pkg/application/autoscaling/karpenter/options.go
*Issue #, if available:* #150
*Description of changes:* Update Karpenter to v0.34.2 and add SpotToSpotConsolidation flag
=> Update Karpenter to v0.34.2 and add SpotToSpotConsolidation flag

cmd/install/ai.go, pkg/application/k8sgpt/k8sgpt.go
Closes #136 
Add `ai-k8sgpt-operator`
=> add: `ai-k8sgpt-operator`

pkg/application/vpc_lattice_controller/options.go, pkg/application/vpc_lattice_controller/vpc_lattice_controller.go
Update `vpc-lattice-controller` to v1.0.4
=> update: `vpc-lattice-controller` to v1.0.4

cmd/create/create.go, cmd/get/get.go, pkg/aws/ssm.go, pkg/resource/ssm/node/get.go, pkg/resource/ssm/node/printer.go, pkg/resource/ssm/node/ssm_node.go, pkg/resource/ssm/session/get.go, pkg/resource/ssm/session/manager.go, pkg/resource/ssm/session/options.go, pkg/resource/ssm/session/printer.go, pkg/resource/ssm/session/ssm_session.go
Refactor SSM code for package naming without underscore
=> cleanup: refactor ssm code for package naming without underscore

pkg/eksctl/eksctl.go, pkg/resource/nodegroup/nodegroup.go, pkg/resource/nodegroup/options.go
- Add SSM parameters for AL2023
- Throw an error if folks try GPU(s) with AL2023
NOTE: you will need a eksctl that supports al2023 as well
=> Add support for AL2023

README.md, cmd/get/get.go, pkg/aws/ec2.go, pkg/resource/ec2/ami/ami.go, pkg/resource/ec2/ami/get.go, pkg/resource/ec2/ami/options.go, pkg/resource/ec2/ami/printer.go
*Issue #, if available:* none
Add `get ami` to view Amazon Machine Images
=> add: `get ami` to view Amazon Machine Images

README.md, pkg/application/autoscaling/cluster_autoscaler/cluster_autoscaler.go, pkg/eksctl/eksctl.go, pkg/resource/cluster/options.go
=> add: support for EKS v1.30

cmd/delete/delete.go, cmd/get/get.go, pkg/resource/ec2/instance/ec2_instance.go, pkg/resource/ec2/instance/get.go, pkg/resource/ec2/instance/manager.go, pkg/resource/ec2/instance/options.go, pkg/resource/ec2/instance/printer.go
Removed underscore from ec2_instance package name
=> cleanup: removed underscore from ec2_instance package name

cmd/create/create.go, pkg/aws/ec2.go, pkg/resource/ec2/instance/ec2_instance.go, pkg/resource/ec2/instance/get.go, pkg/resource/ec2/instance/manager.go, pkg/resource/ec2/instance/options.go, pkg/resource/options.go, pkg/resource/resource.go
=> add: `create ec2-instance`

pkg/application/aws_lb_controller/aws_lb_controller.go, pkg/application/aws_lb_controller/options.go
Update `aws-lb-controller` to v2.8.1
=> update: `aws-lb-controller` to v2.8.1

README.md, pkg/resource/ssm/parameter/get.go
Update `get ssm-parameter` to sort results
=> update: `get ssm-parameter` to sort results

docs/install-karpenter.md, pkg/application/autoscaling/karpenter/default_nodepool.go, pkg/application/autoscaling/karpenter/karpenter.go, pkg/application/autoscaling/karpenter/options.go, pkg/application/options.go, pkg/resource/ssm/parameter/ami_lookup.go, pkg/resource/ssm/parameter/get.go
Update `autoscaling-karpenter` to v0.37.0
=> update: `autoscaling-karpenter` to v0.37.0

docs/install-karpenter.md, pkg/application/kube_prometheus/karpenter_dashboards/capacity_dashboard.go, pkg/application/kube_prometheus/karpenter_dashboards/karpenter_dashboard.go, pkg/application/kube_prometheus/karpenter_dashboards/performance_dashboard.go, pkg/application/kube_prometheus/karpenter_dashboards/service_monitor.go
Update `kube-prometheus-karpenter-dashboards`
=> update: `kube-prometheus-karpenter-dashboards`

.github/workflows/release.yaml, .goreleaser.yml
Update release workflow, pin GoReleaser to v1
=> ci: update release workflow, pin GoReleaser to v1

README.md
Docs: add install instructions for AWS CloudShell and AWS Cloud9
=> docs: add install instructions for AWS CloudShell and AWS Cloud9

cmd/install/install.go, cmd/install/uninstall.go, pkg/application/vault/README.md, pkg/application/vault/options.go, pkg/application/vault/vault.go
Closes #174 
Add (basic) support for Hashicorp Vault
=> Issue 174 vault

pkg/aws/aws.go, pkg/aws/ssm.go, pkg/printer/table.go, pkg/resource/ssm/parameter/get.go, pkg/resource/ssm/parameter/metadata_printer.go, pkg/resource/ssm/parameter/options.go, pkg/resource/ssm/parameter/ssm_parameter.go
Update `get ssm-parameter` lists params in account, new --path option
=> update: `get ssm-parameter` lists params in account, new --path option

cmd/install/crossplane.go, pkg/application/crossplane/ec2/ec2.go
=> add: `crossplane-ec2-provider`

cmd/create/crossplane.go, pkg/resource/crossplane/vpc/vpc.go
=> add: `create crossplane-vpc`

cmd/install/install.go, cmd/install/uninstall.go, docs/install-vpc-lattice-controller.md, pkg/application/vpclattice/gateway_class.go, pkg/application/vpclattice/options.go, pkg/application/vpclattice/security_group_rule.go, pkg/application/vpclattice/vpclattice_controller.go
Update `vpc-lattice-controller` to v1.0.6
=> update: `vpc-lattice-controller` to v1.0.6

docs/create-cluster.md, pkg/resource/cluster/cluster.go, pkg/resource/cluster/options.go
Closes #147 
Add `--encrypt-secrets` flag to `create cluster`
=> add: `--encrypt-secrets` flag to `create cluster`

README.md
docs: README updates for v0.15.0
=> docs: README updates for v0.15.0

.goreleaser.yml, Makefile, cmd/version.go, pkg/version/version.go
Refactor version info so it is available as a package
=> refactor: version info so it is available as a package

Makefile, pkg/application/autoscaling/karpenter/default_nodepool.go, pkg/eksctl/manager.go, pkg/resource/options.go, pkg/version/version.go
Add eksdemo version tags to cluster and node resources
=> add: eksdemo version tags to cluster and node resources

cmd/install/secrets.go, pkg/application/csi/secretsstore/provideraws/provider_aws.go
Add `install secrets-store-csi-driver-provider-aws` aka ASCP
=> add: `install secrets-store-csi-driver-provider-aws` aka ASCP

cmd/install/example.go, pkg/application/csi/secretsstore/secrets_store.go, pkg/application/example/ascp/ascp.go, pkg/application/example/ascp/manifest.go
=> add: `install example-ascp`

pkg/application/k8sgpt/k8sgpt.go
Update `k8sgpt-operator` to v0.1.7
=> update: `k8sgpt-operator` to v0.1.7

cmd/create/create.go, cmd/create/k8sgpt.go, pkg/resource/k8sgpt/bedrock/claudev2/bedrock_claudev2.go
Add `create k8sgpt-bedrock-claudev2`
=> add: `create k8sgpt-bedrock-claudev2`

pkg/application/neuron/deviceplugin/device_plugin.go, pkg/application/neuron/deviceplugin/manifest.go
Update `neuron-device-plugin` for Neuron SDK 2.19.1
=> update: `neuron-device-plugin` for Neuron SDK 2.19.1

cmd/install/autoscaling.go, cmd/install/install.go, cmd/install/uninstall.go, pkg/application/goldilocks/goldilocks.go, pkg/application/goldilocks/options.go
Update `goldilocks` to v4.13.0, remove from `autoscaling`
=> update: `goldilocks` to v4.13.0, remove from `autoscaling`

cmd/install/autoscaling.go, cmd/install/example.go, docs/install-karpenter.md, pkg/application/example/inflate/inflate.go, pkg/application/example/inflate/options.go
Move `autoscaling-inflate` to `example-inflate`
=> move: `autoscaling-inflate` to `example-inflate`

pkg/application/example/ascp/ascp.go, pkg/application/example/ascp/manifest.go, pkg/application/example/ascp/options.go
Update: `example-ascp` with `--json-format` and `--k8s-secret` flags
=> update: `example-ascp` with `--json-format` and `--k8s-secret` flags

README.md
=> docs: updates for v0.16.0

cmd/install/install.go, cmd/install/uninstall.go, pkg/application/aws/lbc/aws_lb_controller.go, pkg/application/aws/lbc/options.go, pkg/resource/cluster/options.go
Update `aws-lb-controller` to v1.8.2
=> update: `aws-lb-controller` to v1.8.2

cmd/install/install.go, cmd/install/uninstall.go, pkg/application/externaldns/external_dns.go, pkg/resource/cluster/options.go
Update: `external-dns` to v0.14.2
=> update: `external-dns` to v0.14.2

README.md, cmd/install/install.go, cmd/install/uninstall.go, pkg/application/spark/options.go, pkg/application/spark/spark_operator.go
=> add: `install spark-operator`

cmd/get/sagemaker.go, go.mod, go.sum, pkg/aws/aws.go, pkg/aws/sagemaker.go, pkg/resource/sagemaker/userprofile/get.go, pkg/resource/sagemaker/userprofile/options.go, pkg/resource/sagemaker/userprofile/printer.go, pkg/resource/sagemaker/userprofile/user_profile.go
=> add: `get sagemaker-user-pool`

cmd/get/get.go, go.mod, go.sum, pkg/aws/efs.go, pkg/resource/efs/filesystem/efs_filesystem.go, pkg/resource/efs/filesystem/get.go, pkg/resource/efs/filesystem/printer.go
=> add: `get efs-filesystem`

pkg/application/ack/apigatewayv2_controller/apigatewayv2_controller.go
Update `ack-apigatewayv2-controller` to v1.0.16
=> update: `ack-apigatewayv2-controller` to v1.0.16

pkg/application/ack/ecr_controller/ecr_controller.go
Update `ack-ecr-controller` to v1.0.18
=> update: `ack-ecr-controller` to v1.0.18

pkg/application/ack/iam_controller/iam_controller.go
Update `ack-iam-controller` to v1.3.12
=> update: `ack-iam-controller` to v1.3.12

pkg/application/ack/prometheusservice_controller/prometheusservice_controller.go
Update `ack-prometheusservice-controller` to v1.2.13
=> update: `ack-prometheusservice-controller` to v1.2.13

pkg/application/ack/s3_controller/s3_controller.go
Update `ack-s3-controller` to v1.0.16
=> update: `ack-s3-controller` to v1.0.16

cmd/install/ack.go, cmd/install/install.go, cmd/install/uninstall.go, pkg/application/ack/rds_controller.go
Add `install ack-rds-controller`
=> add: `install ack-rds-controller`

cmd/install/ack.go, pkg/application/ack/efs_controller.go
Add `install ack-efs-controller`
=> add: `install ack-efs-controller`

cmd/create/ack.go, pkg/resource/ack/efs/filesystem.go
Add `create ack-efs-filesystem`
=> add: `create ack-efs-filesystem`

cmd/create/ack.go, pkg/resource/ack/rds/database_instance.go
Add `create ack-rds-database-instance`
=> add: `create ack-rds-database-instance`

cmd/install/install.go, cmd/install/uninstall.go, pkg/application/certmanager/cert_manager.go, pkg/application/certmanager/cluster_issuer.go
Update `cert-manager` to v1.15.3
=> update: `cert-manager` to v1.15.3

README.md, pkg/application/autoscaling/cluster_autoscaler/cluster_autoscaler.go, pkg/eksctl/eksctl.go, pkg/resource/cluster/options.go
=> add: support for EKS v1.31

pkg/application/karpenter/karpenter.go, pkg/application/karpenter/options.go
=> update: `karpenter` to v1.0.5

cmd/use_cluster.go, cmd/use_context.go, pkg/kubernetes/config.go, pkg/resource/cluster/options.go
Add `use-cluster` command and deprecate `use-context`
=> add: `use-cluster` command and deprecate `use-context`

README.md
Update README for v0.17.0 release
=> docs: update README for v0.17.0 release

pkg/application/options.go, pkg/resource/irsa/options.go
Fixes #255
Create unique IRSA role names across regions
=> fix: create unique IRSA role names across regions

pkg/resource/nodegroup/nodegroup.go, pkg/resource/nodegroup/options.go
pass through the option to eksctl
=> Option to enable EFA when creating cluster

pkg/resource/cluster/cluster.go, pkg/resource/cluster/options.go
I needed to specify pod identity addon, let's allow specifying a list of addons.
=> Allow specifying additional addons

pkg/resource/nodegroup/nodegroup.go
forgot to update the template to use the command line param
=> thread the volume-ops param to template

pkg/resource/nodegroup/nodegroup.go, pkg/resource/nodegroup/options.go
Allow folks who have ODCR or ML Capacity Blocks to use them for demo(s) etc.
=> Allow folks to specify ODCR or ML Capacity blocks

pkg/eksctl/eksctl.go
=> bump eksctl version to 0.205.0
