cmd/install/kubecost.go
Kubecost uninstall had a bug. 
=> Fix uninstall command for kubecost

.github/workflows/build.yaml
Adds a CI workflow which builds eksdemo against Go versions (1.18, 1.19 and 1.20) and runs a smoke test (eksdemo version)
=> Add go build ci workflow

pkg/application/kube_prometheus/kube_prometheus_stack/kube_prometheus_stack.go, pkg/application/kube_prometheus/kube_prometheus_stack/options.go
Update `kube-prometheus-stack` to chart 46.6.0
=> update: `kube-prometheus-stack` to chart 46.6.0

README.md
Fixed verbiage in the README documentation.
=> fix verbiage in README

pkg/helm/helm.go
#64 
`eksdemo` bundles the Helm client and uses it when trying to install software. When the registry is ECR Public, Helm will look for authentication information and send it along with the request. Sometimes, there are stale ECR auth tokens and even though no authentication is required for pulls on ECR public, if the token is expired ECR will return `403 Forbidden`.
This change looks for that error condition, logs out of ECR Public and tries again. This is a change to the user's system though I think it's non destructive because the token is already expired and not valid.
=> fix: logout and try ECR Public pull again when token is expired

cmd/create/cognito.go, pkg/aws/cognito_userpool.go, pkg/resource/cognito/client/app_client.go, pkg/resource/cognito/client/get.go, pkg/resource/cognito/client/manager.go, pkg/resource/cognito/client/options.go
Add `create cognito-app-client`
=> add: `create cognito-app-client`

pkg/resource/cluster/options.go
#31 
Update: `cluster create` defaults to use resource name hostnames
=> update: `cluster create` defaults to use resource name hostnames

pkg/resource/cluster/cluster.go
Update: `create cluster` enables network policy for v1.25+
=> update: `create cluster` enables network policy for v1.25+

pkg/resource/nodegroup/nodegroup.go, pkg/resource/nodegroup/options.go
`create nodegroup` adds taint for GPU and Neuron nodes
Also includes `--no-taints` flag if you don't want the taint
=> update: `create nodegroup` adds taint for GPU and Neuron nodes

pkg/application/neuron/deviceplugin/manifest.go
fix: remove warnings when installing neuron device plugin
=> fix: remove warnings when installing neuron device plugin

pkg/application/external_dns/external_dns.go
*Issue #, if available:* #124 
Updates External DNS `policyDocument` to use `Partition` variable for Route53 hostedzone ARN instead of assuming `aws` partition.
Fixes #124 
=> Fixes external dns stack in non-commercial regions

pkg/resource/cluster/options.go, pkg/resource/nodegroup/options.go
fix: disable AMI lookup for fully private clusters
I haven't yet found a way to support custom AMI for fully private clusters
=> fix: disable AMI lookup for fully private clusters

cmd/install/install.go, cmd/install/uninstall.go, pkg/application/coredumphandler/coredumphandler.go, pkg/application/coredumphandler/options.go
Closes: #122 
Add [core-dump-handler](https://github.com/IBM/core-dump-handler) application that send coredump of binaries into a S3 bucket.
=> Add core-dump-handler

pkg/eksctl/manager.go, pkg/resource/cluster/cluster.go
#138 
use `--disable-nodegroup-eviction` flag when deleting cluster otherwise PDB can prevent node eviction and cluster won't be deleted.
=> fix: delete cluster to use `--disable-nodegroup-eviction` flag

pkg/eksctl/command.go
Add: print eksctl command input during error for troubleshooting
=> add: print eksctl command input during error for troubleshooting

pkg/resource/cluster/cluster.go, pkg/resource/cluster/options.go
*Issue #162 162*
Adds --zones flag as a comma separated value to select zones for eksctl at cluster creation time.
I tested in us-east-1, and was able to select zones. --dry-run also shows the new availabilityZones section in the eksctltemplate.
=> Expose --zones flag for eksctl cluster creation

pkg/application/autoscaling/karpenter/cluster_delete.go
Deleting a cluster shouldn't error if Kubeconfig isn't configured. Changed to show a warning instead about skipping Karpenter resource cleanup.
=> fix: delete cluster shouldn't error if Kubeconfig isn't configured

cmd/install/install.go, cmd/install/uninstall.go, docs/install-hashicorp-consul.md, pkg/application/consul/consul.go, pkg/application/consul/options.go
*Issue #161 *
This adds HashiCorp Consul as a base application install, along with some documentation regarding pre-reqs (EBS CSI, and AWS Load Balancer Controller).
Basic Consul installation to start.
Tested in us-east-1 on a 3 node EKS cluster with both 1 replica and 3 replicas successfully.
=> HashiCorp Consul application

go.mod, go.sum, pkg/aws/ssm.go, pkg/cmd/error.go, pkg/resource/ssm/session/manager.go, pkg/resource/ssm/session/options.go, pkg/resource/ssm/session/ssm_session.go
Add: `create ssm-session` can start a port forwarding session
=> add: `create ssm-session` can start a port forwarding session

cmd/get/get.go, pkg/aws/ssm.go, pkg/resource/ssm/parameter/get.go, pkg/resource/ssm/parameter/printer.go, pkg/resource/ssm/parameter/ssm_parameter.go
Add `get ssm-parameter`
Example
```
eksdemo get ssm-param /aws/service/neuron
+--------+--------------------------------------------------------------------------+-----------------------+
|  Age   |                                   Name                                   |         Value         |
+--------+--------------------------------------------------------------------------+-----------------------+
| 2 days | /aws/service/neuron/dlami/base/amazon-linux-2/latest/image_id            | ami-0e2d585f846ff29f6 |
| 2 days | /aws/service/neuron/dlami/base/ubuntu-20.04/latest/image_id              | ami-02aed491b5681c49e |
| 2 days | /aws/service/neuron/dlami/multi-framework/ubuntu-22.04/latest/image_id   | ami-07f9e2ccc9f0f4103 |
| 2 days | …
```
=> add: `get ssm-parameter`

pkg/cmd/command.go, pkg/resource/ack/amp/logging_configuration.go, pkg/resource/ack/amp/workspace.go, pkg/resource/ack/ec2/security_group.go, pkg/resource/ack/ec2/subnet.go, pkg/resource/ack/ec2/vpc.go, pkg/resource/ack/ecr/ecr.go, pkg/resource/ack/eks/fargate.go, pkg/resource/ack/iam/role.go, pkg/resource/ack/s3/s3.go, pkg/resource/acm_certificate/certificate.go, pkg/resource/addon/addon.go, pkg/resource/amg_workspace/amg_workspace.go, pkg/resource/amp_workspace/amp_workspace.go, pkg/resource/cluster/cluster.go, pkg/resource/cognito/client/app_client.go, pkg/resource/cognito/domain/cognito_domain.go, pkg/resource/cognito/userpool/cognito_userpool.go, pkg/resource/dns_record/dns_record.go, pkg/resource/fargate_profile/fargate_profile.go, pkg/resource/log_group/log_group.go, pkg/resource/log_group/options.go, pkg/resource/nodegroup/nodegroup.go, pkg/resource/nodegroup/spot.go, pkg/resource/options.go, pkg/resource/resource.go, pkg/resource/ssm/session/ssm_session.go, pkg/resource/target_group/target_group.go
Add `CreateArgs` to cmd.Command
Initially it was assumed the arguments to Create, Get, Update and Delete would have the same arguments. But that won't always be the case. For instance, you get EC2 instances by ID, but you don't pass the ID as an argument when creating an EC2 instance.
This allows for different arguments depending on the command. Eventually will break out GetArgs and DeleteArgs.
=> refactor: add CreateArgs to cmd.Command

.devcontainer/devcontainer.json
Add `eksctl`, `kubectl` and `helm` to the dev container
=> dev: add eksctl, kubectl and helm to the dev container

pkg/resource/nodegroup/nodegroup.go
Made a mistake in the previous PR:
- https://github.com/awslabs/eksdemo/pull/171/files#diff-0a673a70f196ec6b6681f6852f6c4ee63bb62a27054dbb077bfba71e9f7c1f47R41
Should instead be around `overrideBootstrapCommand` 
- https://github.com/awslabs/eksdemo/pull/171/files#diff-0a673a70f196ec6b6681f6852f6c4ee63bb62a27054dbb077bfba71e9f7c1f47L60
=> Wrong condition in template for AmazonLinux2023

cmd/create/create.go, cmd/get/get.go, pkg/aws/kms.go, pkg/resource/amp_workspace/manager.go, pkg/resource/error.go, pkg/resource/kms/key/get.go, pkg/resource/kms/key/kms_key.go, pkg/resource/kms/key/manager.go, pkg/resource/kms/key/options.go, pkg/resource/kms/key/printer.go
=> add: `create kms-key`

cmd/install/example.go, pkg/application/example/sparkpi/manifest.go, pkg/application/example/sparkpi/spark_pi.go
Add `install example-spark-pi`
=> add: `install example-spark-pi`

cmd/delete/sagemaker.go, pkg/aws/sagemaker.go, pkg/cmd/error.go, pkg/resource/sagemaker/domain/manager.go, pkg/resource/sagemaker/domain/options.go, pkg/resource/sagemaker/domain/sagemaker_domain.go
=> add: `delete sagemaker domain`

pkg/application/ack/eks_controller/eks_controller.go, pkg/resource/resource.go
Update `ack-eks-controller` to v1.4.5
=> update: `ack-eks-controller` to v1.4.5

cmd/install/ack.go, pkg/application/ack/apigatewayv2_controller.go, pkg/application/ack/ec2_controller.go, pkg/application/ack/ecr_controller.go, pkg/application/ack/eks_controller.go, pkg/application/ack/fargate_pod_role.go, pkg/application/ack/iam_controller.go, pkg/application/ack/prometheusservice_controller.go, pkg/application/ack/rds_controller.go, pkg/application/ack/s3_controller.go
=> refactor: ACK controllers

cmd/install/install.go, cmd/install/uninstall.go, pkg/application/adot/adot_operator.go, pkg/application/adot/collector_service_account.go, pkg/application/adot/options.go, pkg/resource/addon/versions.go, pkg/resource/otel/prometheus_cloudwatch.go, pkg/resource/otel/promethus_amp.go, pkg/resource/otel/simplest.go
Update `adot-operator` to v0.102.0
=> update: `adot-operator` to v0.102.0

cmd/install/argo.go, cmd/install/install.go, cmd/install/uninstall.go, pkg/application/argo/argo_cd/options.go, pkg/application/argo/cd/argo_cd.go, pkg/application/argo/cd/options.go
=> update: `argo-cd` to v2.12.3

pkg/application/karpenter/options.go, pkg/resource/ssm/parameter/ami_lookup.go
Issue #249 
Adds lookups for Bottlerocket AMIs so that the EC2NodeClass is created correctly.
```
$ ./eksdemo install karpenter -c main-lab -a Bottlerocket --dry-run
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
name: default
spec:
amiFamily: Bottlerocket
role: KarpenterNodeRole-main-lab
subnetSelectorTerms:
- tags:
Name: eksctl-main-lab-cluster/SubnetPrivate*
securityGroupSelectorTerms:
- tags:
aws:eks:cluster-name: main-lab
tags:
eksdemo.io/version: v0.16.0-29-g43b91f2-dev
amiSelectorTerms:
- id: ami-09a54b713b931a469
- id: ami-0b07fdee374ab4cf3
```
=> fix: Karpenter 1.0 installation fails when using Bottlerocket

pkg/application/aws/lbc/aws_lb_controller.go
Fix `aws-lb-controller` permissions.
New IAM permissions were required with the upgrade to v2.9.0.
=> fix: `aws-lb-controller` permissions

pkg/resource/nodegroup/options.go
SSM parameter documented here:
- https://aws.amazon.com/blogs/containers/amazon-eks-optimized-amazon-linux-2023-accelerated-amis-now-available/
- https://docs.aws.amazon.com/eks/latest/userguide/retrieve-ami-id.html
=> Support for using AL2023 GPU based AMI(s)

pkg/resource/nodegroup/nodegroup.go, pkg/resource/nodegroup/options.go
defaults are 80 GB with gp3 as before, but folks can use the following with this PR:
```
--volume-size 2048 --volume-type io2
```
Note: for `io2` specifically, we need to specify `volumeIOPS` as well, so hardcoded it for now. we can parameterize it later if more folks start needing to tune it.
=> Add support for specifying volume type/size for node groups

pkg/application/autoscaling/cluster_autoscaler/cluster_autoscaler.go, pkg/eksctl/eksctl.go, pkg/resource/cluster/options.go
- Add 1.32 to list of allowed versions (and as default)
- Update to latest eksctl to be required
- Bump cluster-autoscaler chart as well to support 1.32
Similar to what was filed for 1.31 in https://github.com/awslabs/eksdemo/pull/252
=> Add support for EKS/K8S 1.32

pkg/resource/cluster/cluster.go, pkg/resource/cluster/options.go, pkg/resource/nodegroup/options.go
- eksctl was defaulting to 25 minutes, let's allow a command line param so folks can bump it as needed
- just setting volume type was not enough with the hard-coded 16k iops, making it configurable.
=> Add more command line params - timeout and volume-iops
